# Start from the base image you used
FROM nvcr.io/nvidia/pytorch:24.04-py3

# Set the working directory
WORKDIR /app

# Install the necessary packages
RUN pip install diffusers transformers accelerate safetensors gradio
